name: Auto assign issues

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Assign issues
        uses: gustavofreze/auto-assign@1.0.0
        with:
          assignees: ${{ github.actor }}
          github_token: '${{ secrets.GITHUB_TOKEN }}'
