name: Code quality

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Setup pnpm
        with:
          version: 8

      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - run: pnpm install --frozen-lockfile
      - uses: sibiraj-s/action-eslint@v3
        with:
          working-directory: '/packages'
          token: ${{ secrets.GITHUB_TOKEN }}
          extensions: 'js,jsx,ts,tsx'
          annotations: true
          all-files: true
