name: Code Quality
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: pnpm
      - name: Run ESLint
        run: eslint packages/ --ext .js,.jsx,.ts,.tsx
